Use api instead of dynamic html
mads256h/stregsystemet-rs pull request #19
Opened 2024-09-14 11:26 UTC by henneboy

- Created active products api
- Remove dynamic html generation

2024-09-16 10:06 UTC, mads256h requested changes
Add quick buy call

2024-09-16 10:06 UTC, mads256h commented on src/protocol/products/active_products_response.rs
> +pub struct ActiveProductsReponse {
```suggestion
pub struct ActiveProductsResponse {
```

2024-09-17 08:33 UTC, henneboy commented
@mads256h plz help, github desktop can't reset a branch and I'm not a git user. I cannot fix this without fork...

2024-09-19 12:27 UTC, henneboy commented
@Casper-NS || @miniJmo plz review, thx :)

2024-09-20 10:08 UTC, mads256h approved these changes

2024-09-20 10:09 UTC, merged